### ISSUE TITLE
Add task prioritization feature

### ISSUE THREAD

**Issue by BinaryBrain45** [BinaryBrain45/todo-list#1]
# Add task prioritization feature

## Overview
We need to implement a feature that allows users to set priorities for their todo items. This will help users organize their tasks better.

## Suggested Implementation
- Add a dropdown or buttons next to each task to set priority:
  - High
  - Medium
  - Low
- Use color coding or icons to visually represent priorities
- Allow sorting of tasks based on priority

## Expected Outcome
This feature will enhance the usability of our todo list application by allowing users to:
1. Quickly identify high-priority tasks
2. Sort their todo list based on importance
3. Better manage their time and focus

## Technical Considerations
- Update the `Task` data structure to include a `priority` field
- Modify the UI to display and allow editing of priorities
- Implement a sorting function based on priority

## Additional Notes
- Consider using emojis for visual representation (e.g., 🔴 High, 🟡 Medium, 🟢 Low)
- Ensure the UI remains clean and intuitive after adding this feature

---

:rocket: This enhancement will significantly improve the functionality of our todo list app!

**Comment by Sreedharreddymukkamalla** [comment]
Hi @BinaryBrain45 ,
Can I give it a try
I even have suggestion to change the color of the complete to green onclick

**Comment by BinaryBrain45** [comment]
> Hi @BinaryBrain45 , Can I give it a try I even have suggestion to change the color of the complete to green onclick

Hi @Sreedharreddymukkamalla ,

Thanks for showing interest! You're more than welcome to give it a try. Your suggestion to change the color of the completed tasks to green sounds like a great addition. Feel free to fork the repository, work on the feature, and submit a pull request when you're done.

Let me know if you need any help or clarification on the task.

**Comment by SarthakKashmira** [comment]
Hi @BinaryBrain45 
Can I also give it a try?

**Comment by SarthakKashmira** [comment]
I have opened a PR.Can you review it and merge it?
I have given the colors to the list as per the priorities,like for less->green,medium->orange,high->red.
